version: "2"

services:
  sonarqube:
    image: sonarqube:6.7.4
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=123456
    volumes:
      - /home/docker/sonar/conf:/opt/sonarqube/conf
      - /home/docker/sonar/data:/opt/sonarqube/data
      - /home/docker/sonar/extensions:/opt/sonarqube/extensions
      - /home/docker/sonar/plugins:/opt/sonarqube/lib/bundled-plugins
    depends_on:
      - db
    links:
      - db:db
  db:
    image: postgres
    container_name: sonarqube_postgresql
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=123456
    volumes:
      - /home/docker/postgresql:/var/lib/postgresql
      - /home/docker/postgresql/data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge